services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT:-10091}:3306
  wordpress:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - ${WP_PORT:-10090}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 1 # debut mode == ON
    volumes:
      - ./html:/var/www/html
      - ./shapesns:/var/www/html/wp-content/plugins/shapesns
      - ./wp-cli.yml:/var/www/html/wp-cli.yml

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_ingrid
    restart: always
    depends_on:
      - db
    ports:
      - ${PMA_PORT:-10099}:80
